ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.governance_token_trap]
path = "out/GovernanceTokenTrap.sol/GovernanceTokenTrap.json"
# Replace with the deployed address of the Response contract
response_contract = "0x0000000000000000000000000000000000000000"
response_function = "onTrapTriggered(bytes)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = []